{% set name = "pyiwfm" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: PLACEHOLDER_SHA256

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyiwfm = pyiwfm.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - numpy >=1.23
    - pandas >=2.0
    - h5py >=3.7
    - jinja2 >=3.0

test:
  imports:
    - pyiwfm
    - pyiwfm.core
    - pyiwfm.io
    - pyiwfm.components
  commands:
    - pyiwfm --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hatch-tyler/pyiwfm
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python package for IWFM (Integrated Water Flow Model) models
  description: |
    pyiwfm provides tools for reading, writing, visualizing, and comparing
    IWFM models developed by the California Department of Water Resources.
  dev_url: https://github.com/hatch-tyler/pyiwfm
  doc_url: https://hatch-tyler.github.io/pyiwfm/

extra:
  recipe-maintainers:
    - hatch-tyler
